//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Builder_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblForm()
        {
            this.tblInputInForms = new HashSet<tblInputInForm>();
        }
    
        public int formId { get; set; }
        public string formName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInputInForm> tblInputInForms { get; set; }
        public tblForm(string _formName)
        {
            this.formName = _formName;
        }
    }
}
