//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Builder_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSubmission
    {
        public int userId { get; set; }
        public int formId { get; set; }
        public int positionInForm { get; set; }
        public System.DateTime submissionDate { get; set; }
        public string userInput { get; set; }
    
        public virtual tblInputInForm tblInputInForm { get; set; }
        public tblUserSubmission()
        {

        }
        public tblUserSubmission(int _userId, int _formId,int _positionInForm,DateTime _submissionDate, string _userInput)
        {
            this.userId = _userId;
            this.formId = _formId;
            this.positionInForm = _positionInForm;
            this.submissionDate = _submissionDate;
            this.userInput = _userInput;
        }
    }
}
